apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: html-loadbalancer
spec:
  replicas: 2
  selector:
    matchLabels:
      name: html-loadbalancer
  template:
    metadata:
      name: html-loadbalancer
      labels:
        name: html-loadbalancer
    spec:
      containers:
        - name : html-loadbalancer
          image: dimarhanung/web-profile:v1
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: statichtml-service-loadbalancer
spec:
  type: LoadBalancer
  selector: 
    name: html-loadbalancer
  ports:
    - port: 80
      targetPort: 80 