apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: html-nodeport
spec:
  replicas: 2
  selector:
    matchLabels:
      name: html-nodeport
  template:
    metadata:
      name: html-nodeport
      labels:
        name: html-nodeport
    spec:
      containers:
        - name : html-nodeport
          image: dimarhanung/web-profile:v1
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: statichtml-service-nodeport
spec:
  type: NodePort
  selector: 
    name: html-nodeport
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
